name: kin6839_lab
channels:
  - pariterre
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - biorbd
  - casadi
  - seaborn
  - matplotlib
  - scipy
  - pyqt
  - vtk
  - pyomeca
  - biorbd-viz
