name: kin6839_lab
channels:
  - conda-forge
  - pariterre
dependencies:
  - python=3.6
  - numpy
  - biorbd
  - casadi
  - seaborn
  - matplotlib
  - scipy
  - pyqt
  - vtk
  - pyomeca
  - biorbd-viz=1.1.0
